### PR TITLE
Non default versions

### LINKED ISSUE #304: plugin is broken for non maven default version schemes
`versions:use-latest-versions` is broken if your version scheme is not following the maven default scheme (`major`.`minor`.inremental`-`buildNumber/qualifer`).

The ordering and searching for newer versions happens correctly however the `MajorMinorIncrementalFilter` filters out all results as all versions are treated as a `qualifier` and they are never updated`

You also get strange results if you have some versions that conform to the version and yet some that do not, meaning you actually get updates that are not the latest.

(e.g. in the following the update from 1.1.1.1 goes first to 1.8.1xx and then when run again to 2.138.0.2

```
$ mvn versions:use-latest-versions -Dincludes=com.example*:my-app* -Dexcludes=com.example.common:my-app-bom
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building My App 2.138.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.6:use-latest-versions (default-cli) @ my-app-server ---
[INFO] Major version changes allowed
[INFO] Major version changes allowed
[INFO] Updated com.example.common:my-app-agent:jar:1.1.1.1 to version 1.8.110
[INFO] Updated com.example.server:my-app-sublicensing:jar:1.1.1.1 to version 1.8.103
[INFO] Updated com.example.common:my-app-context:jar:1.1.1.1 to version 1.8.108
[INFO] Updated com.example.server:my-app-license:jar:1.1.1.1 to version 1.8.103
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.753 s
[INFO] Finished at: 2018-08-31T10:25:51+01:00
[INFO] Final Memory: 30M/367M
[INFO] ------------------------------------------------------------------------

$ mvn versions:use-latest-versions -Dincludes=com.example*:my-app* -Dexcludes=com.example.common:my-app-bom
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building My App 2.138.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.6:use-latest-versions (default-cli) @ my-app-server ---
[INFO] Major version changes allowed
[INFO] Major version changes allowed
[INFO] Updated com.example.common:my-app-agent:jar:1.8.110 to version 2.138.0.2
[INFO] Updated com.example.server:my-app-sublicensing:jar:1.8.103 to version 2.138.0.2
[INFO] Updated com.example.common:my-app-context:jar:1.8.108 to version 2.138.0.2
[INFO] Updated com.example.server:my-app-license:jar:1.8.103 to version 2.138.0.2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.723 s
[INFO] Finished at: 2018-08-31T10:25:57+01:00
[INFO] Final Memory: 30M/374M
[INFO] ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jtnord**
Fixes the incorrect logic in the `MajorMinorIncrementalFilter` that caused numerous issues.

Fixes #304 for which tests are included and this was targetted.

I also beleive (and there is some minimal test for it) #296 #295 #282 

ITs pass on maven `3.5.2`  as the ordering and parsing relies on some fixes in Maven 3.x they may or may not pass on maven 2.x.

@stephenc @khmarbaise @olamy

### CODE REVIEW

File: src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java [hunk 1]
```diff
@@ -106,22 +106,11 @@ else if ( artifactVersion.getIncrementalVersion() != selectedVersion.getIncremen
                     }
                 }
             }
-            else if(selectedVersion.getQualifier() != null){
```
Comment (jtnord) [inline src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java]: regression was introduced in #276

File: src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java [hunk 2]
```diff
@@ -106,22 +106,11 @@ else if ( artifactVersion.getIncrementalVersion() != selectedVersion.getIncremen
...
-                if(selectedVersion.getQualifier().contentEquals("SNAPSHOT")){
-                    if ( !versionsToUse.contains( artifactVersion ) )
-                    {
-                            versionsToUse.add( artifactVersion );
-                    }
-                }
-            }
-            else
-            {
-                if ( allowMajorUpdates && allowMinorUpdates && allowIncrementalUpdates )
```
Comment (jtnord) [inline src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java]: we do not need to check these, if the major minor or incremental version had changed we would not reach this `else`  thus what we have left is a qualifier or build number

**Comment by jtnord** [comment]
test failure looks like infrastructure issues.

```
ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.14:check (check-java17) on project versions-maven-plugin: Failed to check signatures: Unexpected end of ZLIB input stream -> [Help 1]
```

**Comment by olamy** [comment]
@khmarbaise except any concern I will merge it.
let use know.
Thanks

**Comment by khmarbaise** [comment]
If it fixes issues which is the case get it and merge it....
